### ISSUE TITLE
New rsyslog 3.0.0 upstream cookbook not compatible with chef 11+

### ISSUE THREAD

**Issue by drenalin23** [chef-cookbooks/bluepill#25]
By not locking the rsyslog cookbook version in metadata.rb, Berkshelf will upgrade to the latest rsyslog 3.0.0 cookbook (released on 11/10/15) which now depends upon the compat_resources cookbook.  The compat_resources cookbook only works with Chef 12+.

Need to either lock your metadata.rb version and/or bump the version number here so that you have versions compatible with chef 11+ and chef 12+, or decide to label as only compatible with chef 12+.

**Comment by tas50** [comment]
I've release 2.4.1 to use rsyslog 2.0.  The next release of this cookbook will move to Chef 12 only though as the LWRP will be converted a custom resource.
