### ISSUE TITLE
latest version 2.4.2 is not chef 11 compatible

### ISSUE THREAD

**Issue by arussel** [chef-cookbooks/bluepill#28]
see comment in https://github.com/chef-cookbooks/bluepill/commit/d6ecce20344bc1e355a1cad13428c7b06557d313#commitcomment-16259521 not sure if this was wanted, but if it is, README need to be updated

**Comment by arussel** [comment]
ping @tas50

**Comment by tas50** [comment]
Since its' shipped at this point it's a bit too late.  I've noted in the README and the CHANGELOG that this cookbook now requires Chef 12.  You'll want to pin to 2.4.1 to preserve Chef 11 compatibility.
