### ISSUE TITLE
Ohai doesn't return value.

### ISSUE THREAD

**Issue by yurylevin** [chef-cookbooks/bluepill#35]
https://github.com/chef-cookbooks/bluepill/blob/178239cdf2ee77d122294df833a78a72394ff3d6/attributes/default.rb#L18

Value node['languages']['ruby']['bin_dir'] is nil. If workaround https://github.com/chef-cookbooks/bluepill/blob/178239cdf2ee77d122294df833a78a72394ff3d6/.kitchen.yml#L24 is removed, then test kitchen fails with error

Errno::ENOENT
-------------
No such file or directory - /bluepill

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/bluepill/resources/service.rb:69:in `block (2 levels) in class_from_file'
/tmp/kitchen/cache/cookbooks/bluepill/resources/service.rb:68:in `block in class_from_file'

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/bluepill_test/recipes/default.rb

 15: bluepill_service node['bluepill_test']['service_name'] do
 16:   action [:enable, :load, :start]
 17: end

**Comment by cheeseplus** [comment]
I am not sure this is a bug so much as working as intended. The default value for the `default['bluepill']['bin']` asks Ohai for a Ruby but if you have a specific Ruby (like Chef's embedded) you would set that similarly to what you are doing in kitchen. It's seems a sensible default as most people running bluepill will be using another Ruby as opposed to the Chef embedded one.

**Comment by tas50** [comment]
I'm with Seth on this. This is actually working as intended if you don't have a Ruby installed
