### ISSUE TITLE
 require 'chef/mixin/language' deprecated as  part of 14.0 chef

### ISSUE THREAD

**Issue by ISHA7782** [chef-cookbooks/bluepill#36]
### Cookbook version
4.1.0

### Chef-client version
14.1.1

### Platform Details
Amazon EC2 cloud Ubuntu 16.04

### Scenario:
While running chef client, failing with compilation error 
cannot load such file -- chef/mixin/language
Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/bluepill/resources/service.rb:23:in `class_from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/bluepill/resources/service.rb:

 16:  # See the License for the specific language governing permissions and
 17:  # limitations under the License.
 18:  #
 19:
 20:  property :service_name, name_property: true
 21:  property :variables, Hash
 22:
 23>> require 'chef/mixin/language'
 24:
 25:  action :start do
 26:    unless service_running?
 27:      converge_by("start #{new_resource.service_name}") do
 28:        shell_out!(start_command)
 29:      end
 30:    end
 31:  end
 32:

### Steps to Reproduce:
Run chef client with 14.0 or plus chef 

### Expected Result:
Removal of require 'chef/mixin/language' as it is deprecated

**Comment by mike10010100** [comment]
Bump. Running into this problem as well.

**Comment by tas50** [comment]
@ISHA7782 @mike10010100 Can you please open a PR to remove this code from the service resource.
